### PR TITLE
Added exception for Docker around systemd and enabling services at boot

### PR DESCRIPTION
**Pull request by ventz**
This is exceptions for:

* router/services.yml
and
* smrt/services.yml

@dylanjacob ^ ping - I think this covers your pull request + the second half.

### CODE REVIEW

**Comment by dylanjacob** [comment]
@ventz would it be more efficient to put the logic in the main.yml for both router and smrt so that it is just one check that would bypass services.yml altogether?

**Comment by ventz** [comment]
@dylanjacob Yea - that's a good point. I thought main.yml generates the tokens, but it looks like that has been separated to it's own task now (awesome!)

so https://github.com/csirtgadgets/cif-ansible-role/blob/master/tasks/smrt/main.yml is the only place that needs it?

**Comment by ventz** [comment]
@dylanjacob Ah - I see that you submitted as PR already :)

Closing this one then.

**Comment by dylanjacob** [comment]
@ventz In my testing, I've inserted the line:
`  when: DOCKER_BUILD is undefined or DOCKER_BUILD == 'no'`
into the main.yml in _both_ `tasks/router/main.yml` and `tasks/smrt/main.yml` to skip the services.yml for each.

I think the one for router has already been merged in #5 and thats why I added #6 to take care of smrt.
Aside from this, I have a pull request in csirtgadgets/bearded-avenger-deploymentkit#41 to skip the nginx restart via systemd. With all of these changes I can get ansible to complete successfully. I'm working on tweaking a few things in my fork of docker-cif, namely restarting the nginx service as part of the entrypoint script. I'm getting `unauthorized` when I try to do anything though....we're getting close though!

**Comment by ventz** [comment]
@dylanjacob I noticed that for some reason the token file is not properly setup - assuming that has to do with the unauthorized you are getting. The router config is also not being setup for some reason.

**Comment by dylanjacob** [comment]
@ventz that aligns with what I'm seeing here. Shall we create an issue in ventz/docker-cif to discuss further?

**Comment by ventz** [comment]
@dylanjacob Sounds good. I was going to propose to close up existing issues that are "semi-to-do with cif and/or docker" and start one thread we can use to get everything sorted out in order to get to the latest version.

**Pull request closed without merging**
